# Generated by Django 3.0.2 on 2021-06-23 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sg_sosial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IniUsrProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=200)),
                ('nama_belakang', models.CharField(max_length=200)),
                ('foto_profile', models.ImageField(upload_to='poto_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
