# Generated by Django 3.0.2 on 2021-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0002_iniusrprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniusrprofile',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='poto_profile/'),
        ),
        migrations.AlterField(
            model_name='iniusrprofile',
            name='nama_belakang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='iniusrprofile',
            name='nama_depan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
