# Generated by Django 3.0.2 on 2021-06-26 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sg_sosial.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sg_sosial', '0003_auto_20210626_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusGuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('status_foto', models.ImageField(blank=True, null=True, upload_to=sg_sosial.models.fldr_usr_foto)),
                ('status_video', models.FileField(blank=True, null=True, upload_to=sg_sosial.models.fldr_usr_video)),
                ('status_tanggal', models.DateField()),
                ('status_suka', models.IntegerField(blank=True, max_length=10000, null=True)),
                ('status_komen', models.IntegerField(blank=True, max_length=10000, null=True)),
                ('status_bagi', models.IntegerField(blank=True, max_length=10000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StatusGuna', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
