# Generated by Django 3.0.2 on 2021-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0004_statusguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='status_bagi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_komen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_suka',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
