# Generated by Django 3.0.2 on 2021-06-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0005_auto_20210626_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='status_bagi',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_komen',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_suka',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
