# Generated by Django 3.0.2 on 2021-06-26 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0006_auto_20210626_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='status_bagi',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_komen',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_suka',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
