# Generated by Django 3.0.2 on 2021-06-27 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0007_auto_20210626_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='status_tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
