# Generated by Django 3.0.2 on 2021-06-28 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sg_sosial.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sg_sosial', '0008_auto_20210627_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusguna',
            name='foto_pp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StatusGuna', to='sg_sosial.IniUsrProfile'),
        ),
        migrations.AlterField(
            model_name='iniusrprofile',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to=sg_sosial.models.fldr_usr_pp),
        ),
        migrations.RemoveField(
            model_name='statusguna',
            name='status_bagi',
        ),
        migrations.AddField(
            model_name='statusguna',
            name='status_bagi',
            field=models.ManyToManyField(blank=True, related_name='status_bagi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='statusguna',
            name='status_komen',
        ),
        migrations.AddField(
            model_name='statusguna',
            name='status_komen',
            field=models.ManyToManyField(blank=True, related_name='status_komen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='statusguna',
            name='status_suka',
        ),
        migrations.AddField(
            model_name='statusguna',
            name='status_suka',
            field=models.ManyToManyField(blank=True, related_name='status_suka', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KomenGuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isiKomen', models.TextField()),
                ('tanggal_komen', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KomenGuna', to='sg_sosial.StatusGuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
