# Generated by Django 3.0.2 on 2021-06-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0010_auto_20210628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='foto_pp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_pp', to='sg_sosial.IniUsrProfile'),
        ),
    ]
