# Generated by Django 3.0.2 on 2021-06-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0011_auto_20210628_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusguna',
            name='foto_pp',
        ),
    ]
