# Generated by Django 3.0.2 on 2021-06-29 02:15

from django.db import migrations, models
import django.db.models.deletion
import sg_sosial.models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0012_remove_statusguna_foto_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusguna',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to=sg_sosial.models.fldr_usr_pp),
        ),
        migrations.AddField(
            model_name='statusguna',
            name='st_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sg_sosial.IniUsrProfile'),
        ),
    ]
