# Generated by Django 3.0.2 on 2021-06-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0013_auto_20210629_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusguna',
            name='foto_profile',
        ),
    ]
