# Generated by Django 3.0.2 on 2021-06-29 02:22

from django.db import migrations, models
import sg_sosial.models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0014_remove_statusguna_foto_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusguna',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to=sg_sosial.models.fldr_usr_pp),
        ),
    ]
