# Generated by Django 3.0.2 on 2021-06-29 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0016_auto_20210629_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='st',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StatusGuna', to='sg_sosial.IniUsrProfile'),
        ),
    ]
