# Generated by Django 3.0.2 on 2021-06-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0017_auto_20210629_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='st',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StatusGuna', to='sg_sosial.IniUsrProfile'),
            preserve_default=False,
        ),
    ]
