# Generated by Django 3.0.2 on 2021-06-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0019_auto_20210630_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KomenGuna', to='sg_sosial.IniUsrProfile'),
        ),
    ]
