# Generated by Django 3.0.2 on 2021-07-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0021_auto_20210701_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='isiKomen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_bagi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_suka',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
