# Generated by Django 3.0.2 on 2021-07-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0022_auto_20210701_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='isiKomen',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
