# Generated by Django 3.0.2 on 2021-07-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0023_auto_20210701_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='status_bagi',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_suka',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
