# Generated by Django 3.0.2 on 2021-07-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0024_auto_20210701_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusguna',
            name='status_bagi',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statusguna',
            name='status_suka',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
