# Generated by Django 3.0.2 on 2021-07-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0025_auto_20210701_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sg_sosial.IniUsrProfile'),
        ),
    ]
