# Generated by Django 3.0.2 on 2021-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0026_auto_20210701_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='isiKomen',
            field=models.TextField(null=True),
        ),
    ]
