# Generated by Django 3.0.2 on 2021-07-01 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sg_sosial', '0029_auto_20210701_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='komenguna',
            name='st_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='KomenGuna', to='sg_sosial.IniUsrProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komenguna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KomenGuna', to=settings.AUTH_USER_MODEL),
        ),
    ]
