# Generated by Django 3.0.2 on 2021-07-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0031_auto_20210701_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='isiKomen',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
