# Generated by Django 3.0.2 on 2021-07-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_sosial', '0033_auto_20210701_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komenguna',
            name='isiKomen',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
